const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
let model, io, engine;
const initialized = Promise.all([import('../src/lib/music-motion/model.js'), import('../src/lib/music-motion/io.js'), import('../local-agent/music-motion-engine.mjs')]).then(([m,i,e])=>{model=m;io=i;engine=e;});
function fullProject(seconds=16) {
  const p=model.newProject();p.audio={asset_id:'audio',sha256:'a'.repeat(64),duration_seconds:seconds};
  p.analysis={audio:{sha256:'a'.repeat(64)},transcription:{acoustic:{coverage:{complete:true,decoded_seconds:seconds,processed_seconds:seconds},sections:[{id:'s',label:'Section 1',start:0,end:seconds}]}}};
  p.scenes=model.createScenesFromAnalysis(p);p.scenes[0].prompt='Avance lentement, caméra latérale.';p.scenes[0].keyframe_id='image';p.shots=model.splitScenes(p,8);p.review.storyboard=true;return p;
}
test('No fabricated fallback: full acoustic coverage and source hash are required',async()=>{await initialized;const p=fullProject();assert.equal(model.analysisReady(p),true);p.audio.sha256='b'.repeat(64);assert.equal(model.analysisReady(p),false);assert.throws(()=>model.createScenesFromAnalysis(p),/Analyse acoustique/);p.audio.sha256='a'.repeat(64);p.analysis.transcription.acoustic.coverage.processed_seconds=4;assert.equal(model.analysisReady(p),false);});
test('Balanced shots cover the entire song and never exceed the selected duration',async()=>{await initialized;const p=fullProject(233.89);assert.equal(p.shots.length,30);assert.equal(model.intervalIssues(p.shots,233.89).length,0);assert.ok(p.shots.every(s=>s.end-s.start<=8));assert.equal(p.shots.at(-1).end,233.89);});
test('Imported eight scenes do not magically become four minutes of video',async()=>{await initialized;const p=fullProject(233.89);assert.equal(model.coverage(p).seconds,0);assert.equal(model.coverage(p).missing,233.89);assert.ok(model.renderIssues(p).length);});
test('Gaps, overlaps, duplicates and non-finite boundaries are rejected',async()=>{await initialized;for(const scenes of [[{id:'a',start:1,end:4}],[{id:'a',start:0,end:3},{id:'b',start:2,end:4}],[{id:'a',start:0,end:2},{id:'a',start:2,end:4}],[{id:'a',start:0,end:NaN}]])assert.ok(model.intervalIssues(scenes,4).length);});
test('An image cannot satisfy video coverage; animatic is explicit',async()=>{await initialized;const p=fullProject(8);p.assets=[{id:'image',mime:'image/png'}];assert.ok(model.renderIssues(p).some(x=>/vidéo/.test(x)));assert.equal(model.renderIssues(p,{animatic:true}).length,0);assert.equal(model.coverage(p).seconds,0);});
test('Short videos and source in-points are checked against decoded duration',async()=>{await initialized;const p=fullProject(8);p.assets=[{id:'v',mime:'video/mp4',duration_seconds:5}];p.shots[0].video_id='v';assert.ok(model.renderIssues(p).some(x=>/courte/.test(x)));assert.equal(model.coverage(p).seconds,5);p.assets[0].duration_seconds=9;p.shots[0].source_in=2;assert.ok(model.renderIssues(p).length);});
test('Chat action whitelist and scene locks cannot be overridden by model text',async()=>{await initialized;const p=fullProject();assert.throws(()=>model.validateAction({type:'shell',command:'anything'},p));p.scenes[0].locked=true;assert.throws(()=>model.validateAction({type:'update_scene',scene_id:p.scenes[0].id,patch:{prompt:'x'}},p),/verrouillée/);const result=model.validateAction({type:'update_scene',scene_id:(p.scenes[0].locked=false,p.scenes[0].id),patch:{prompt:'x',locked:false,command:'x'}},p);assert.deepEqual(result.patch,{prompt:'x'});});
test('Storyboard proposals must cover all the music',async()=>{await initialized;const p=fullProject();assert.throws(()=>model.validateAction({type:'storyboard',sections:[{start:0,end:5}]},p),/couvre/);});
test('Project normalization removes credentials and executable-looking fields',async()=>{await initialized;const p=fullProject();p.analysis.api_key='must-not-export';p.analysis.nested={token:'secret',data:'kept'};const clean=model.normalizeProject(p);assert.equal(clean.analysis.api_key,undefined);assert.deepEqual(clean.analysis.nested,{data:'kept'});});
test('Timecodes retain decimals and reject invalid minute/second notation',async()=>{await initialized;assert.equal(model.parseTime('03:53.89'),233.89);assert.equal(model.parseTime('01:02:03,50'),3723.5);assert.ok(Number.isNaN(model.parseTime('01:99')));});
test('ZIP reader/writer preserve Unicode and bytes',async()=>{await initialized;const packed=await io.writeZip(new Map([['été/prompt.txt',new Blob(['demain — création'])],['media/test.bin',new Blob([new Uint8Array([0,255,4])])]]));const read=await io.readZip(packed);assert.equal(await read.get('été/prompt.txt').text(),'demain — création');assert.deepEqual([...new Uint8Array(await read.get('media/test.bin').arrayBuffer())],[0,255,4]);});
test('ZIP traversal, absolute paths and scripts are never executed',async()=>{await initialized;for(const name of ['../secret','C:/file','/root','a\\b','a/../b'])assert.throws(()=>io.safeArchivePath(name));const archive=await io.writeZip(new Map([['run.js',new Blob(['throw new Error("must not execute")'])]]));await assert.rejects(()=>io.importProjectZip(new File([archive],'pack.zip')),/Aucun storyboard/);});
test('Corrupt ZIP bytes fail CRC rather than loading altered files',async()=>{await initialized;const zip=await io.writeZip(new Map([['image.txt',new Blob(['hello'])]]));const bytes=new Uint8Array(await zip.arrayBuffer());bytes[39]^=0xff;await assert.rejects(()=>io.readZip(new Blob([bytes])),/Intégrité/);});
test('Native project archive roundtrips media and prompts, without blob URLs',async()=>{await initialized;const p=model.newProject();const {asset,blob}=await io.makeAsset(new File([Buffer.from([137,80,78,71,13,10,26,10])],'ref.png',{type:'image/png'}),'reference');p.assets=[asset];const packed=await io.exportProjectZip(p,new Map([[asset.id,blob]]));const restored=await io.importProjectZip(new File([packed],'project.zip'));assert.equal(restored.project.id,p.id);assert.equal(restored.blobs.size,1);assert.equal(restored.project.assets[0].sha256,asset.sha256);assert.equal(restored.project.review.storyboard,false);});
test('Legacy numbered ZIP maps scene, image, video prompt and CSV timecodes',async()=>{await initialized;const zip=await io.writeZip(new Map([['PACK/01_IMAGES/01_Intro.png',new Blob([Buffer.from([137,80,78,71,13,10,26,10])])],['PACK/03_MONTAGE/01_TABLEAU_MONTAGE.csv',new Blob(['scene;titre;image;timecode\n01;Intro;01_Intro.png;00:00 → 00:29\n'])],['PACK/02_PROMPTS_SCENES/01_INTRO.txt',new Blob(['PROMPT IMAGE FIXE\nUn hall sombre.\n\nPROMPT VIDÉO / ANIMATION GROK\nTravelling lent.\n\nCAMÉRA\n24 mm\n'])]]));const r=await io.importProjectZip(new File([zip],'legacy.zip'));assert.equal(r.project.scenes.length,1);assert.equal(r.project.scenes[0].end,29);assert.equal(r.project.scenes[0].prompt,'Travelling lent.');assert.ok(r.project.scenes[0].keyframe_id);assert.equal(r.project.audio,null);assert.equal(r.project.shots.length,0);});
test('Local workspace creates one idempotent job and rejects conflicting reuse',async()=>{await initialized;const root=await fs.mkdtemp(path.join(os.tmpdir(),'mm-test-'));try{const w=await new engine.Workspace(root).init();const results=await Promise.all([w.createJob({request_id:'same',type:'image',prompt:'a'}),w.createJob({request_id:'same',type:'image',prompt:'a'})]);assert.equal(results.filter(r=>r.created).length,1);await assert.rejects(()=>w.createJob({request_id:'same',type:'image',prompt:'b'}),/Conflit|Identifiant/);await w.recover();assert.equal((await w.job('same')).status,'failed');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('Opaque media paths and executable rejection',async()=>{await initialized;assert.throws(()=>engine.checkedId('../asset'));assert.throws(()=>engine.detectMedia(Buffer.from('MZ executable'),'video.mp4'));assert.equal(engine.detectMedia(Buffer.from([137,80,78,71,13,10,26,10]),'a.exe')[0],'image/png');});
test('Frame-accurate render validation rejects holes, stills and short clips',async()=>{await initialized;const a=new Map([['v',{mime:'video/mp4',has_video:true,duration_seconds:4}],['i',{mime:'image/png'}]]);const spec={duration_seconds:4,fps:25,shots:[{asset_id:'v',start:0,end:4}]};assert.equal(engine.validateRender(spec,a).shots[0].frames,100);assert.throws(()=>engine.validateRender({...spec,shots:[{asset_id:'v',start:.1,end:4}]},a),/trou/);assert.throws(()=>engine.validateRender({...spec,shots:[{asset_id:'i',start:0,end:4}]},a),/animatique/);assert.throws(()=>engine.validateRender({...spec,shots:[{asset_id:'v',start:0,end:4,source_in:1}]},a),/courte/);});
test('SRT times and untrusted markup are normalized without inventing words',async()=>{await initialized;const result=engine.makeSrt([{start:65.1,end:67.25,text:'Bonjour <b>demain</b>'}],100);assert.match(result,/00:01:05,100 --> 00:01:07,250/);assert.ok(!result.includes('<b>'));assert.equal(engine.makeSrt([{start:-1,end:8,text:'wrong'}],4),'');});
test('Local image workflow uses the reference and only known nodes',async()=>{await initialized;const {buildImageWorkflow}=await import('../local-agent/music-motion-service.mjs');const d=buildImageWorkflow({prompt:'a',format:'16:9'},'installed.safetensors','ref.png');assert.equal(d.workflow['8'].inputs.image,'ref.png');assert.equal(d.workflow['5'].inputs.denoise,.35);assert.equal(d.workflow['4'].class_type,'VAEEncode');assert.equal(d.output_node,'7');});
test('Standalone storyboard JSON preserves the source and records original text',async()=>{await initialized;const p=fullProject(8);const file=new File([JSON.stringify({sections:[{label:'Import',start:0,end:8,video_prompt:'Caméra lente'}]})],'storyboard.json',{type:'application/json'});const r=await io.importStoryboardJson(file,p);assert.equal(r.scenes[0].prompt,'Caméra lente');assert.equal(p.audio.asset_id,'audio');assert.ok(r.source.text.includes('Caméra lente'));});
test('Active HTML and SVG media are rejected in portable manifests',async()=>{await initialized;for(const mime of ['text/html','image/svg+xml','application/javascript']){const p=model.newProject();p.assets=[{id:'x',name:'danger',mime}];assert.throws(()=>model.normalizeProject(p),/Type de média/);}});

test('ZIP import verifies the real audio/video durations before installing the project',async()=>{await initialized;const p=fullProject(80);p.assets=[{id:'audio',name:'song.wav',mime:'audio/wav',sha256:'a'.repeat(64),duration_seconds:80},{id:'video',name:'shot.mp4',mime:'video/mp4',duration_seconds:90}];const blobs=new Map([['audio',new Blob(['audio'])],['video',new Blob(['video'])]]);let i=0;const r=await io.verifyImportedMedia({project:p,blobs,warnings:[]},async()=>({duration_seconds:++i===1?8:5}));assert.equal(r.project.audio.duration_seconds,8);assert.equal(r.project.assets[1].duration_seconds,5);assert.equal(r.project.analysis,null);assert.equal(p.audio.duration_seconds,80);assert.ok(r.warnings.length);await assert.rejects(()=>io.verifyImportedMedia({project:p,blobs,warnings:[]},async()=>({duration_seconds:0})),/Durée réelle/);});
