export const PLATFORM_SERVICES = Object.freeze({
  publicSite: Object.freeze({
    title: "Site public JS-Innov.IA",
    url: "https://www.jsinnovia.com",
    domain: "www.jsinnovia.com",
    hosting: "Railway",
    service: "js-innovia-site",
    repository: "Julien218/jsinnovia",
    repositoryUrl: "https://github.com/Julien218/jsinnovia",
    branch: "main",
    status: "official",
    note: "Site officiel destiné aux visiteurs et aux clients.",
  }),
  cockpit: Object.freeze({
    title: "Cockpit central",
    url: "https://cockpit.jsinnovia.com",
    domain: "cockpit.jsinnovia.com",
    hosting: "Railway",
    service: "cockpit-v3",
    repository: "Julien218/js-innov.ia-cockpit",
    repositoryUrl: "https://github.com/Julien218/js-innov.ia-cockpit",
    branch: "main",
    status: "official",
    note: "Administration privée de JS-Innov.IA.",
  }),
  signageManager: Object.freeze({
    title: "Signelya — gestion d’affichage dynamique",
    url: "https://olivier-signage-cockpit-production.up.railway.app/ecran-geant",
    domain: "olivier-signage-cockpit-production.up.railway.app",
    hosting: "Railway",
    service: "olivier-signage-cockpit",
    repository: "Julien218/js-innov.ia-cockpit",
    repositoryUrl: "https://github.com/Julien218/js-innov.ia-cockpit",
    branch: "feature/olivier-signage-pilot-release",
    status: "module",
    note: "Module spécialisé relié au Cockpit, distinct du site public.",
  }),
  signageProductSite: Object.freeze({
    title: "Vitrine produit Signage",
    url: "https://olivier-signage-site-production.up.railway.app",
    domain: "olivier-signage-site-production.up.railway.app",
    hosting: "Railway",
    service: "olivier-signage-site",
    repository: "Julien218/js-innov.ia",
    repositoryUrl: "https://github.com/Julien218/js-innov.ia",
    branch: "feature/digital-signage-product-release",
    status: "module",
    note: "Adresse Railway technique du produit Signage. Ce n’est pas le site général JS-Innov.IA.",
  }),
});

export const PLATFORM_SERVICE_LIST = Object.freeze(Object.values(PLATFORM_SERVICES));
