package ia.jsinnov.pixeliumplayer;

import android.app.*; import android.os.*; import android.content.*; import android.graphics.Color; import android.net.Uri; import android.view.*; import android.widget.*;
import org.json.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*;

public class MainActivity extends Activity {
  static final String DEFAULT_SERVER="https://olivier-signage-cockpit-production.up.railway.app";
  final Handler handler=new Handler(Looper.getMainLooper()); VideoView video; TextView status; String token, server; File cacheDir; int itemIndex=0; JSONArray items=new JSONArray();
  @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);hideSystemUi();cacheDir=new File(getFilesDir(),"media");cacheDir.mkdirs();loadConfig();}
  void hideSystemUi(){getWindow().getDecorView().setSystemUiVisibility(5894|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
  void loadConfig(){android.content.SharedPreferences p=getSharedPreferences("player",0);token=p.getString("token","");server=p.getString("server",DEFAULT_SERVER);if(token.isEmpty())showSetup();else showPlayer();}
  TextView label(String s){TextView v=new TextView(this);v.setText(s);v.setTextColor(Color.WHITE);v.setTextSize(18);v.setPadding(12,12,12,12);return v;}
  void showSetup(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(60,40,60,40);box.setBackgroundColor(Color.rgb(10,10,20));box.addView(label("Pixelium Player — association sécurisée"));EditText url=new EditText(this);url.setText(server);url.setTextColor(Color.WHITE);url.setHint("Adresse du cockpit");box.addView(url);EditText key=new EditText(this);key.setTextColor(Color.WHITE);key.setHintTextColor(Color.GRAY);key.setHint("Jeton Player affiché dans le cockpit");box.addView(key);Button save=new Button(this);save.setText("Associer ce Player");box.addView(save);save.setOnClickListener(v->{String k=key.getText().toString().trim(),u=url.getText().toString().trim().replaceAll("/$","");if(k.length()<20){Toast.makeText(this,"Jeton invalide",Toast.LENGTH_LONG).show();return;}getSharedPreferences("player",0).edit().putString("token",k).putString("server",u).apply();token=k;server=u;showPlayer();});setContentView(box);}
  void showPlayer(){FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);video=new VideoView(this);root.addView(video,new FrameLayout.LayoutParams(-1,-1));status=label("Pixelium Player — connexion…");status.setBackgroundColor(0xAA000000);FrameLayout.LayoutParams sp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);root.addView(status,sp);setContentView(root);video.setOnCompletionListener(mp->playNext());video.setOnErrorListener((mp,w,e)->{status.setText("Lecture impossible — conservation du cache précédent");handler.postDelayed(this::playNext,5000);return true;});heartbeat();}
  void heartbeat(){new Thread(()->{try{JSONObject request=new JSONObject().put("appVersion","0.1.0-pilot").put("diagnostics",new JSONObject().put("android",Build.VERSION.RELEASE).put("model",Build.MODEL).put("freeBytes",cacheDir.getFreeSpace()));JSONObject response=jsonRequest(server+"/api/signage/player/heartbeat","POST",request);JSONObject publication=response.optJSONObject("publication");if(publication!=null)syncPublication(publication);ui("Player connecté — prochain contrôle dans 30 s");}catch(Exception e){ui("Hors connexion — lecture du dernier contenu valide");playCached();}finally{handler.postDelayed(this::heartbeat,30000);}}).start();}
  void syncPublication(JSONObject pub)throws Exception{JSONObject manifest=pub.getJSONObject("manifest");JSONArray incoming=manifest.optJSONArray("items");if(incoming==null||incoming.length()==0)return;JSONArray ready=new JSONArray();for(int i=0;i<incoming.length();i++){JSONObject item=incoming.getJSONObject(i),media=item.optJSONObject("media");if(media==null)continue;String id=media.getString("id"),url=media.optString("url"),name=media.optString("name",id+".mp4");String ext=name.contains(".")?name.substring(name.lastIndexOf('.')):".mp4";File target=new File(cacheDir,id+ext);if(!target.exists()){File tmp=new File(cacheDir,id+".part");download(url,tmp);if(!tmp.renameTo(target))throw new IOException("Activation cache impossible");}item.put("localPath",target.getAbsolutePath());ready.put(item);}if(ready.length()==0)return;getSharedPreferences("player",0).edit().putString("playlist",ready.toString()).apply();items=ready;itemIndex=0;handler.post(this::playNext);jsonRequest(server+"/api/signage/player/publications/"+pub.getString("id")+"/ack","POST",new JSONObject().put("status","active"));}
  void download(String source,File target)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(source).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(60000);try(InputStream in=c.getInputStream();FileOutputStream out=new FileOutputStream(target)){byte[] b=new byte[65536];int n;while((n=in.read(b))>0)out.write(b,0,n);}finally{c.disconnect();}}
  void playCached(){try{String raw=getSharedPreferences("player",0).getString("playlist","[]");items=new JSONArray(raw);if(items.length()>0)handler.post(this::playNext);}catch(Exception ignored){}}
  void playNext(){if(items.length()==0)return;try{JSONObject item=items.getJSONObject(itemIndex++%items.length());String path=item.optString("localPath");video.setVideoURI(Uri.fromFile(new File(path)));video.start();status.setText("Lecture Pixelium — cache local actif");}catch(Exception e){handler.postDelayed(this::playNext,3000);}}
  void ui(String s){handler.post(()->status.setText(s));}
  JSONObject jsonRequest(String target,String method,JSONObject body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(target).openConnection();c.setRequestMethod(method);c.setConnectTimeout(10000);c.setReadTimeout(20000);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.toString().getBytes(StandardCharsets.UTF_8));}InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();String text=new String(readAll(in),StandardCharsets.UTF_8);if(c.getResponseCode()>=400)throw new IOException("HTTP "+c.getResponseCode()+" "+text);return new JSONObject(text);}
  byte[] readAll(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))>0)out.write(b,0,n);return out.toByteArray();}
}

